import AppKit
import Carbon.HIToolbox
import Combine

/// One clipboard entry. Text is stored inline; images as PNG files next to the
/// history; file copies as URL strings.
struct ClipItem: Codable, Identifiable, Equatable {
    enum Kind: String, Codable { case text, image, files }
    let id: UUID
    var date: Date
    let kind: Kind
    var text: String?          // .text: the content; .files: joined display names
    var imageFile: String?     // .image: file name inside the images folder
    var fileURLs: [String]?    // .files
    var sourceApp: String?     // bundle id of the app that was frontmost

    var preview: String {
        switch kind {
        case .text:  return (text ?? "").trimmingCharacters(in: .whitespacesAndNewlines)
        case .image: return "Image"
        case .files: return (fileURLs ?? []).map { URL(fileURLWithPath: $0).lastPathComponent }.joined(separator: ", ")
        }
    }
}

/// Clipboard history (the Windows Win+V thing). Watches the general pasteboard,
/// keeps the last N items on disk, and shows a popup to search and paste one.
///
/// Privacy: content flagged by the source app as concealed or transient
/// (password managers, autofill) is never recorded, and recording pauses while
/// a known password manager is frontmost.
final class ClipboardFeature: Feature, ObservableObject, @unchecked Sendable {
    private let d = UserDefaults.standard
    private let pasteboard = NSPasteboard.general
    private var timer: Timer?
    private var lastChangeCount = -1
    private var ownChangeCount = -1
    private var hotKeyID: UInt32?
    private var saveWork: DispatchWorkItem?
    private var panelStorage: ClipboardPanel?
    @MainActor private var panel: ClipboardPanel {
        if let p = panelStorage { return p }
        let p = ClipboardPanel(feature: self)
        panelStorage = p
        return p
    }

    /// Newest first. Mutated on the main thread only.
    @Published private(set) var items: [ClipItem] = []

    init() { items = load() }

    // MARK: Settings

    var maxItems: Int { get { let v = d.integer(forKey: "clipMax"); return v == 0 ? 200 : v } set { d.set(newValue, forKey: "clipMax"); trim() } }
    var pauseForPasswordManagers: Bool { get { d.object(forKey: "clipPausePW") as? Bool ?? true } set { d.set(newValue, forKey: "clipPausePW") } }
    var hotKey: KeyCombo {
        get {
            if let data = d.data(forKey: "clipHotKey"), let c = try? JSONDecoder().decode(KeyCombo.self, from: data) { return c }
            // Control+V: on an external keyboard with the modifier swap, that is the physical Win+V.
            return KeyCombo(keyCode: UInt32(kVK_ANSI_V), modifiers: UInt32(controlKey))
        }
        set {
            if let data = try? JSONEncoder().encode(newValue) { d.set(data, forKey: "clipHotKey") }
            if timer != nil { registerHotKey() }
        }
    }

    private let passwordManagers: Set<String> = [
        "com.1password.1password", "com.agilebits.onepassword7", "com.agilebits.onepassword-osx",
        "com.bitwarden.desktop", "com.apple.Passwords", "com.apple.keychainaccess",
        "com.lastpass.LastPass", "com.dashlane.Dashlane", "com.keepassxc.keepassxc",
    ]

    // MARK: Feature lifecycle

    @discardableResult
    func start() -> Bool {
        guard timer == nil else { return true }
        lastChangeCount = pasteboard.changeCount
        let t = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        RunLoop.main.add(t, forMode: .common)
        timer = t
        registerHotKey()
        return true
    }

    func stop() {
        timer?.invalidate(); timer = nil
        if let id = hotKeyID { HotKeyCenter.shared.unregister(id); hotKeyID = nil }
    }

    private func registerHotKey() {
        if let id = hotKeyID { HotKeyCenter.shared.unregister(id) }
        hotKeyID = HotKeyCenter.shared.register(hotKey) { [weak self] in
            MainActor.assumeIsolated { self?.togglePanel() }
        }
    }

    // MARK: Capture

    @MainActor
    private func poll() {
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count
        guard count != ownChangeCount else { return }   // our own paste

        let types = pasteboard.types ?? []
        let flagged: Set<NSPasteboard.PasteboardType> = [
            NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
            NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
            NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        ]
        guard flagged.isDisjoint(with: types) else { return }

        let source = NSWorkspace.shared.frontmostApplication?.bundleIdentifier
        if pauseForPasswordManagers, let source, passwordManagers.contains(source) { return }

        var item: ClipItem?
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL], !urls.isEmpty {
            let paths = urls.map(\.path)
            item = ClipItem(id: UUID(), date: Date(), kind: .files, text: nil, imageFile: nil, fileURLs: paths, sourceApp: source)
        } else if let text = pasteboard.string(forType: .string), !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            item = ClipItem(id: UUID(), date: Date(), kind: .text, text: text, imageFile: nil, fileURLs: nil, sourceApp: source)
        } else if let image = NSImage(pasteboard: pasteboard), let png = Self.png(image) {
            let name = UUID().uuidString + ".png"
            try? png.write(to: Self.imagesDir.appendingPathComponent(name))
            item = ClipItem(id: UUID(), date: Date(), kind: .image, text: nil, imageFile: name, fileURLs: nil, sourceApp: source)
        }
        guard var new = item else { return }

        // Same content copied again: move the existing entry to the top.
        if let idx = items.firstIndex(where: { $0.kind == new.kind && $0.text == new.text && $0.fileURLs == new.fileURLs }),
           new.kind != .image {
            new = items.remove(at: idx)
            new.date = Date()
        }
        items.insert(new, at: 0)
        trim()
        scheduleSave()
    }

    private static func png(_ image: NSImage) -> Data? {
        guard let tiff = image.tiffRepresentation, let rep = NSBitmapImageRep(data: tiff) else { return nil }
        return rep.representation(using: .png, properties: [:])
    }

    private func trim() {
        guard items.count > maxItems else { return }
        let dropped = items[maxItems...]
        for item in dropped { deleteImage(item) }
        items.removeLast(items.count - maxItems)
        scheduleSave()
    }

    // MARK: Generators (UUID / nanoid), for the popup

    var uuidUppercase: Bool { get { d.bool(forKey: "clipUUIDUpper") } set { d.set(newValue, forKey: "clipUUIDUpper") } }
    var nanoidLength: Int { get { let v = d.integer(forKey: "clipNanoidLen"); return v == 0 ? 21 : v } set { d.set(newValue, forKey: "clipNanoidLen") } }

    func newUUID() -> String {
        let u = UUID().uuidString
        return uuidUppercase ? u : u.lowercased()
    }

    /// nanoid: URL-safe alphabet (A-Za-z0-9_-), cryptographically random, default 21 chars.
    func newNanoid() -> String {
        let alphabet = Array("useandom-26T198340PX75pxJACKVERYMINDBUSHWOLF_GQZbfghjklqvwyzrict")
        var rng = SystemRandomNumberGenerator()
        return String((0..<max(1, nanoidLength)).map { _ in alphabet[Int(rng.next() % UInt64(alphabet.count))] })
    }

    /// Generate a value, record it, and paste it into the frontmost app.
    @MainActor
    func generateAndPaste(_ text: String) {
        let item = ClipItem(id: UUID(), date: Date(), kind: .text, text: text, imageFile: nil, fileURLs: nil, sourceApp: Bundle.main.bundleIdentifier)
        items.insert(item, at: 0)
        trim()
        paste(item)
    }

    // MARK: Actions

    @MainActor
    func togglePanel() { panel.isVisible ? panel.close() : panel.show() }

    @MainActor
    func showPanel() { panel.show() }

    /// Put the item on the clipboard and paste it into the frontmost app.
    @MainActor
    func paste(_ item: ClipItem) {
        pasteboard.clearContents()
        switch item.kind {
        case .text:
            pasteboard.setString(item.text ?? "", forType: .string)
        case .image:
            if let name = item.imageFile, let img = NSImage(contentsOf: Self.imagesDir.appendingPathComponent(name)) {
                pasteboard.writeObjects([img])
            }
        case .files:
            pasteboard.writeObjects((item.fileURLs ?? []).map { URL(fileURLWithPath: $0) as NSURL })
        }
        ownChangeCount = pasteboard.changeCount
        lastChangeCount = ownChangeCount

        // Move to the top (it is now the current clipboard).
        if let idx = items.firstIndex(of: item) {
            var moved = items.remove(at: idx)
            moved.date = Date()
            items.insert(moved, at: 0)
            scheduleSave()
        }

        panel.close()
        // Give the previous app a moment to be key again, then send ⌘V.
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.08) {
            let src = CGEventSource(stateID: .combinedSessionState)
            let down = CGEvent(keyboardEventSource: src, virtualKey: CGKeyCode(kVK_ANSI_V), keyDown: true)
            let up = CGEvent(keyboardEventSource: src, virtualKey: CGKeyCode(kVK_ANSI_V), keyDown: false)
            down?.flags = .maskCommand
            up?.flags = .maskCommand
            down?.post(tap: .cghidEventTap)
            up?.post(tap: .cghidEventTap)
        }
    }

    @MainActor
    func delete(_ item: ClipItem) {
        deleteImage(item)
        items.removeAll { $0.id == item.id }
        scheduleSave()
    }

    @MainActor
    func clear() {
        for item in items { deleteImage(item) }
        items = []
        scheduleSave()
    }

    // MARK: Storage (~/Library/Application Support/Filip's Mac Fixes/)

    private static var dir: URL {
        let base = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first!
        let dir = base.appendingPathComponent("Filip's Mac Fixes", isDirectory: true)
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir
    }
    static var imagesDir: URL {
        let dir = Self.dir.appendingPathComponent("Clipboard Images", isDirectory: true)
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir
    }
    private static var file: URL { dir.appendingPathComponent("clipboard.json") }

    private func load() -> [ClipItem] {
        guard let data = try? Data(contentsOf: Self.file),
              let list = try? JSONDecoder().decode([ClipItem].self, from: data) else { return [] }
        return list
    }

    private func scheduleSave() {
        saveWork?.cancel()
        let snapshot = items
        let work = DispatchWorkItem {
            if let data = try? JSONEncoder().encode(snapshot) {
                try? data.write(to: Self.file, options: .atomic)
            }
        }
        saveWork = work
        DispatchQueue.global(qos: .utility).asyncAfter(deadline: .now() + 0.5, execute: work)
    }

    private func deleteImage(_ item: ClipItem) {
        if let name = item.imageFile {
            try? FileManager.default.removeItem(at: Self.imagesDir.appendingPathComponent(name))
        }
    }
}
